### ISSUE TITLE
Error with get_args_man() on win and mac

### ISSUE THREAD

**Issue by rcheatsheet** [jannes-m/RQGIS#22]
Hi,

tried to use get_args_man() on a win-machine from within RStudio.
```
 env <- set_env('C:\\Program Files\\QGIS Lyon')
 args <- get_args_man(alg = "qgis:joinattributesbylocation", 
                       options = TRUE,
                        qgis_env = env)
```
This produced following error:
```
 Error in file(file, "rt") : cannot open the connection
 In addition: Warning messages:
 1: running command 'batch_cmd.cmd' had status 1 
 2: In file(file, "rt") :
 cannot open file 'C:\Users\user\AppData\Local\Temp\RtmpOCWJmK/output.csv': No such file or # directory
```
Seems to be a forward/backslash problem '\RtmpOCWJmK/output.csv'

On my mac using:
```
env <- set_env()
```
produced
```
find: /usr/local/Cellar/: No such file or directory
Warnmeldung:
Ausführung von Kommando 'find /usr/local/Cellar/ -name 'QGIS.app'' ergab Status 1 
```
but
```
env <- set_env('/Applications/QGIS.app')
```
worked, but get_args_man() produced the following message

```
sh: sysctl: command not found
sh: grep: command not found
sh: sw_vers: command not found
sh: grep: command not found
Error in sys.excepthook:
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/Resources/python/qgis/utils.py", line 171, in qgis_excepthook
    showException(type, value, tb, None, messagebar=True)
  File "/Applications/QGIS.app/Contents/Resources/python/qgis/utils.py", line 82, in showException
    open_stack_dialog(type, value, tb, msg)
  File "/Applications/QGIS.app/Contents/Resources/python/qgis/utils.py", line 117, in open_stack_dialog
    iface.messageBar().popWidget()
AttributeError: 'NoneType' object has no attribute 'messageBar'

Original exception was:
Traceback (most recent call last):
  File "py_cmd.py", line 33, in <module>
    vals.append(param.getValueAsCommandLineParameter())
  File "/Applications/QGIS.app/Contents/Resources/python/plugins/processing/core/parameters.py", line 593, in getValueAsCommandLineParameter
    ParameterString.ESCAPED_NEWLINE)) + '"'
AttributeError: 'NoneType' object has no attribute 'replace'
Fehler in file(file, "rt") : kann Verbindung nicht öffnen
Zusätzlich: Warnmeldungen:
1: Ausführung von Kommando 'sh batch_cmd.sh' ergab Status 1 
2: In file(file, "rt") :
  kann Datei '/var/folders/2j/jdxbpssn2075kpg880jv78w40000gn/T//Rtmpidy5o1/output.csv' nicht öffnen: No such file or directory
```

**Comment by jannes-m** [comment]
Hi,

in fact it is not a backward/forward slash problem. Actually it is recommend to use the long-term release of QGIS, i.e. QGIS 2.14. When you install it, please follow the instructions found under `vignette("install_guide", package = "RQGIS")`. I ran your "qgis:joinattributesbylocation"-example using Windows and QGIS 2.14, and it worked fine. Let me know if this solves your problem.

**Comment by rcheatsheet** [comment]
Hi,

yes, you are totally right. In fact it was a rtfm-problem. Installed LTS-QGIS on my mac and everything works like a charm. Will try on monday on my win machine and let you know if it works. Sorry for any inconvenience!

**Comment by pat-s** [comment]
@rcheatsheet how did you install QGIS on your Mac? It is recommended to use the homebrew cask way as recommended in the vignette. For me this works fine even with the most current version.
I assume you installed QGIS using the kingchaos binary? This is interesting for us, i.e. we should consider adding a warning message if this case is detected (however we then should first figure out how to distinguish between such different QGIS installation approaches).

**Comment by rcheatsheet** [comment]
@pat-s yes, been lazy and used the KyngChaos version (for reinstalling QGIS). The two functions `find_algorithms()` and  `get_args_man()` basically did what they should. So i didn't bother about any other errors thrown. Nevertheless there were some, but i wanted to dive deeper into RQGIS first and see if the errors cause any further problems.

```
> env <- set_env('/Applications/QGIS.app')
> find_algorithms("join", name_only = TRUE, qgis_env = env)
QSqlDatabase: QSQLITE driver not loaded
QSqlDatabase: available drivers: 
QSqlQuery::prepare: database not open
sh: sysctl: command not found
sh: grep: command not found
sh: sw_vers: command not found
sh: grep: command not found
Failed `CDLL(/opt/local/lib/libgeos_c.dylib)`
[1] "ERROR: Opening of authentication db FAILED" "WARNING: Auth db query exec() FAILED"       "qgis:joinattributesbylocation"              "qgis:joinattributestable"                  
[5] ""                                          
> get_args_man(alg = "qgis:joinattributesbylocation", 
+                        options = TRUE,
+                        qgis_env = env)
QSqlDatabase: QSQLITE driver not loaded
QSqlDatabase: available drivers: 
QSqlQuery::prepare: database not open
sh: sysctl: command not found
sh: grep: command not found
sh: sw_vers: command not found
sh: grep: command not found
Failed `CDLL(/opt/local/lib/libgeos_c.dylib)`
$TARGET
[1] "None"

$JOIN
[1] "None"

$PREDICATE
[1] "None"

$PRECISION
[1] "0.0"

$SUMMARY
[1] "0"

$STATS
[1] "\"sum,mean,min,max,median\""

$KEEP
[1] "0"

$OUTPUT
[1] "None"
```

**Comment by rcheatsheet** [comment]
Runs also with QGIS 2.14 LTS on windows machine.
